### ISSUE TITLE
Stability issues

### ISSUE THREAD

**Issue by Hoeze** [nullp0tr/bluew#12]
Hi,
I'm getting some errors from time to time, e.g.:
```
devices = bluew.devices()
for i in devices:
    print(i)
```
Result:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 3, in <module>
  File "/usr/local/lib/python3.5/dist-packages/bluew/ppobj.py", line 31, in __str__
    keys = self.__dict__
  File "/usr/local/lib/python3.5/dist-packages/bluew/device.py", line 58, in __getattribute__
    self = bluew.info(mac)  # noqa: F841
  File "/usr/local/lib/python3.5/dist-packages/bluew/api.py", line 130, in info
    return engine.info(mac)
  File "/usr/local/lib/python3.5/dist-packages/bluew/dbusted/decorators.py", line 24, in _wrapper
    return func(self, dev, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bluew/dbusted/decorators.py", line 33, in _wrapper
    available = self._is_device_available(dev)
  File "/usr/local/lib/python3.5/dist-packages/bluew/dbusted/dbusted.py", line 479, in _is_device_available
    self._stop_scan()
  File "/usr/local/lib/python3.5/dist-packages/bluew/dbusted/dbusted.py", line 344, in _stop_scan
    adiface = BluezAdapterInterface(self._bus, self.cntrl)
  File "/usr/local/lib/python3.5/dist-packages/bluew/dbusted/interfaces.py", line 86, in __init__
    BLUEZ_SERVICE_PATH + self.cntrl)
TypeError: Can't convert 'NoneType' object to str implicitly
```
Sorry for spamming issues :)

**Comment by nullp0tr** [comment]
I'll investigate this tomorrow, definitely is a bug. And no worries about spamming, feel more than free to fire both issues and contributions:)
