### ISSUE TITLE
error on scan and get devices

### ISSUE THREAD

**Issue by bjoernh** [nullp0tr/bluew#14]
Hey, i try to scan for devices and i run into following error:
```
bluew.devices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/bluew/api.py", line 32, in devices
    return engine.devices
  File "/tmp/bluew/dbusted/dbusted.py", line 126, in devices
    return boiface.get_devices()
  File "/tmp/bluew/dbusted/interfaces.py", line 615, in get_devices
    devices = tuple(map(lambda obj: Device(**obj), objects))
  File "/tmp/bluew/dbusted/interfaces.py", line 615, in <lambda>
    devices = tuple(map(lambda obj: Device(**obj), objects))
  File "/tmp/bluew/device.py", line 28, in __init__
    super().__init__(Device.attrs, **kwargs)
  File "/tmp/bluew/ppobj.py", line 23, in __init__
    name = self.__class__.__name__
  File "/tmp/bluew/device.py", line 57, in __getattribute__
    mac = super().__getattribute__('address')
AttributeError: 'Device' object has no attribute 'address'
```

**Comment by nullp0tr** [comment]
Thanks for the report, I'll be looking into this over the weekend!

**Comment by nullp0tr** [comment]
Just to keep you up to date, I've been a bit busy but planning to check this issue very soon.

**Comment by sim6** [comment]
#17 works for me also. Please, could you release a new version?
